import { Reveal } from "./Reveal";

const stats = [
  { value: "₹2.4 Cr+", label: "Revenue Generated by Users" },
  { value: "85,000+", label: "Hours Saved Across All Users" },
  { value: "340+", label: "Automation Workflows Deployed" },
  { value: "10,000+", label: "Creators Using Our Templates" },
];

export function Stats() {
  return (
    <section className="border-y bg-white">
      <div className="mx-auto max-w-7xl px-6 py-20 md:py-24">
        <Reveal>
          <h2 className="mx-auto max-w-3xl text-center text-3xl font-bold tracking-tight md:text-4xl">
            Trusted By 10,000+ Digital Creators Worldwide
          </h2>
        </Reveal>
        <div className="mt-12 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
          {stats.map((s, i) => (
            <Reveal key={s.label} delay={i * 0.08}>
              <div className="card-surface p-7">
                <div className="text-3xl font-extrabold tracking-tight md:text-4xl">
                  {s.value}
                </div>
                <div className="mt-2 text-sm text-muted-foreground">{s.label}</div>
              </div>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  );
}